First draft of a manpage in Markdown format.
bepaald/signalbackup-tools pull request #55
Opened 2022-01-23 17:26 UTC by tomperrine

This is a first draft of a man page for the signalbackup-tool.

It has many flaws and bugs, but has re-factored the info from the README into arguments, selectors, etc.

I have not yet dived into the code to get info on the un-documented arguments, etc.

2022-12-08 23:44 UTC, Meteor0id commented
Maybe add a warning / notion that using this tool means unencrypted Signal chats hit your disk, and could leave forensic traces. Signal was after all designed to never leave anything unencrypted, so this tool should be used with the consideration that your chats are less secure when you use this tool.

2022-12-09 07:16 UTC, bepaald commented
Note that this program should not cause your data to hit your disk unless:
1. Explicitly asked for it (for example [Dump unencrypted database to disk](https://github.com/bepaald/signalbackup-tools#dump))
2. Your RAM is full (probably from other processes) and things are written to swap. This program shouldn't use a lot of RAM (not like the entire backup is read in there, just piece by piece when needed). I could investigate using [mlockall](https://man7.org/linux/man-pages/man2/mlock.2.html) to prevent this program from ever swapping, but I have no experience with this. I think swapping is pretty rare these days, but on systems that regularly swap due to low RAM, the user may not even appreciate a program using `mlock`.

So, maybe this note is not necessary? I think both of the above conditions are pretty much implied when working with a program like this. On the other hand, it can't hurt.

2022-12-15 23:20 UTC, Willdickem requested changes

2022-12-15 23:20 UTC, Willdickem commented on signalbackup-tool.md
> +# REPORTING BUGS
It's on my phone

2022-12-15 23:20 UTC, Willdickem commented on signalbackup-tool.md
> +# REPORTING BUGS
-

2023-01-28 13:22 UTC, closed without merging